---
name: Run Against A Self Hosted Runner
on:
  # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch
  - workflow_dispatch
jobs:
  basic:
    name: Execute a Basic Task
    runs-on:
      - self-hosted
    steps:
      - run: |
          sudo touch /root/.ghar
          sudo ls -lah /root

      - run: |
          podman run --rm --tty quay.io/podman/hello

      - run: |
          ls -lah
          podman build --tag a:1 .
          podman run --rm --tty a:1 cat /date.txt
