---
name: Run Against A Self Hosted Runner
on:
  # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch
  - workflow_dispatch
jobs:
  basic:
    name: Execute a Basic Task
    runs-on:
      - self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Test sudo inside the runner
        run: |
          sudo touch /root/.ghar
          sudo ls -lah /root

      - name: Test our favorite container runtime
        run: |
          podman run --rm --tty quay.io/podman/hello

      - name: Build and run an image with our favorite container runtime
        run: |
          ls -lah
          podman build --tag a:1 .
          podman run --rm --tty a:1 cat /date.txt
